[build]
  base = "frontend"
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  VITE_API_URL = "https://event-11.onrender.com"
  REACT_APP_API_URL = "https://event-11.onrender.com"
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

